version: '3.5'
services:
       php:
        image: php:8.1.6-apache
        container_name: php
        volumes:
            - '/var/www/html/api'
        ports:
            - "80:80"
        links:
            - db
       db:
          image: mysql:latest
          container_name: mysql-
          volumes:
            - './db/mysqsl:/var/lib/mysql'
          ports:
            - "3306:3306"
          environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'transferencia'


